## some pickers
define-command -hidden open-buffer-picker %{
  prompt buffer: -menu -buffer-completion %{
    buffer %val{text}
  }
}

define-command -hidden open-file-picker %{
  prompt file: -menu -shell-script-candidates 'fd --type=file' %{
    edit -existing %val{text}
  }
}

define-command -hidden open-rg-picker %{
  prompt search: %{
    prompt refine: -menu -shell-script-candidates "rg -in '%val{text}'" %{
      eval "edit -existing  %sh{(cut -d ' ' -f 1 | tr ':' ' ' ) <<< $kak_text}"
    }
  }
}

map global user f :open-file-picker<ret>
map global user b :open-buffer-picker<ret>
map global user g :open-rg-picker<ret>

# spaces
set-option global indentwidth 4

# tmux mappings
map global normal <c-h> ":tmux-terminal-horizontal kak -c %val{session}<ret>"
map global normal <c-v> ":tmux-terminal-vertical kak -c %val{session}<ret>"

# tab handling
map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><a-lt>'

colorscheme base16

add-highlighter /global number-lines -relative

set-option -add global ui_options terminal_assistant=none

hook global WinCreate .*\.c %{ set-option global makecmd "make" }
hook global WinCreate .*\.go %{ set-option global makecmd "go build" }
hook global WinCreate .*\.(cc|cpp|cxx) %{ set-option global makecmd "cmake" }
