(deftheme winter
  "Created 2024-04-27.")

(custom-theme-set-faces
 'winter
 '(default ((t (:family "JetBrainsMono Nerd Font" :foundry "JB" :width normal :height 98 :weight medium :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#e3e6e8" :background "#0d1216" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#80bfff"))))
 '(fixed-pitch ((t (:family "JetBrainsMono Nerd Font" :foundry "JB" :width normal :height 110 :weight medium :slant normal))))
 '(variable-pitch ((t (:family "JetBrainsMono Nerd Font" :foundry "JB" :width normal :height 110 :weight medium :slant normal))))
 '(escape-glyph ((t (:weight bold :foreground "#dfbf9f"))))
 '(homoglyph ((t (:weight bold :foreground "#efbf8f"))))
 '(minibuffer-prompt ((t (:foreground "#9fbfdf"))))
 '(highlight ((t (:underline (:color foreground-color :style line :position nil) :foreground "#e3e6e8" :background "#21262c"))))
 '(region ((t (:extend t :foreground "#e3e6e8" :background "#29333d"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:extend t :foreground "#e3e6e8" :background "#21262c"))))
 '(trailing-whitespace ((t (:foreground "#e3e6e8" :background "#ff8080"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#9f9fdf"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#b6c2ce"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#e3e6e8"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:slant italic :foreground "#efbf8f"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#8ac6f2"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#9fdf9f"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#9f9fdf"))))
 '(font-lock-variable-name-face ((t (:foreground "#e3e6e8"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#ccaa8f"))))
 '(button ((t (:foreground "#e3e6e8" :background "#243342"))))
 '(link ((t (:underline (:color foreground-color :style line :position nil) :foreground "#8ac6f2"))))
 '(link-visited ((t (:underline (:color foreground-color :style line :position nil) :foreground "#afafcf"))))
 '(fringe ((t (:background "#303030"))))
 '(header-line ((t (:foreground "#e7f6da" :background "#303030"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#e3e6e8" :background "#21262c"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#b6c2ce" :style released-button)))))
 '(mode-line-inactive ((t (:foreground "#b6c2ce" :background "#0d1216"))))
 '(isearch ((t (:foreground "#b6c2ce" :background "#0d1216"))))
 '(isearch-fail ((t (:background "#ff8080"))))
 '(lazy-highlight ((t (:foreground "#a0a8b0" :background "#384048"))))
 '(match ((t (:background "#afafcf"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'winter)
